### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by RealDoigt** [RealDoigt/raylib_misc#16]
So raylib_misc use is now down to zero again --- at least I haven't heard from anyone in a long while so this is a good moment while I'm cleaning up old issues and preparing the transition to make this a dub package, I figure this is a good time to rename the project to something more meaningful. Any ideas? I was thinking of "DOOR" for "D Object Oriented Raylib", but if someone's got something better in mind...

**Comment by colinkiama** [comment]
The only suggestion I can think of is "rayliboop" (Raylib + OOP). Somewhat playful if that's what you're going for (Last part sounds like "boop").

Otherwise, I think DOOR is fine.

**Comment by schveiguy** [comment]
I like DOOR. I'm sorry, I don't like rayliboop. when I first glanced at it, I thought it said raylibpoop...

**Comment by RealDoigt** [comment]
ok so DOOR it is then!
